/*

 EXPORT.H

 Include File.

 Info:
  Form                 : Each tile separate.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 24

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define TileLabelBank 0
extern unsigned char TileLabelTLE0[];
extern unsigned char TileLabelTLE1[];
extern unsigned char TileLabelTLE2[];
extern unsigned char TileLabelTLE3[];
extern unsigned char TileLabelTLE4[];
extern unsigned char TileLabelTLE5[];
extern unsigned char TileLabelTLE6[];
extern unsigned char TileLabelTLE7[];
extern unsigned char TileLabelTLE8[];
extern unsigned char TileLabelTLE9[];
extern unsigned char TileLabelTLE10[];
extern unsigned char TileLabelTLE11[];
extern unsigned char TileLabelTLE12[];
extern unsigned char TileLabelTLE13[];
extern unsigned char TileLabelTLE14[];
extern unsigned char TileLabelTLE15[];
extern unsigned char TileLabelTLE16[];
extern unsigned char TileLabelTLE17[];
extern unsigned char TileLabelTLE18[];
extern unsigned char TileLabelTLE19[];
extern unsigned char TileLabelTLE20[];
extern unsigned char TileLabelTLE21[];
extern unsigned char TileLabelTLE22[];
extern unsigned char TileLabelTLE23[];
extern unsigned char TileLabelTLE24[];

/* End of EXPORT.H */
